# Generated by Django 3.1.5 on 2021-04-27 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_seconds', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('podcast_name', models.CharField(max_length=100)),
                ('duration_seconds', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('duration_seconds', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('podcast', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.podcastfile')),
            ],
        ),
    ]
