# Generated by Django 3.1.5 on 2021-04-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='podcast',
        ),
        migrations.AddField(
            model_name='podcastfile',
            name='participant',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.participants'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
