# Generated by Django 3.1.5 on 2021-04-29 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20210429_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='max_participant',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
