# Generated by Django 3.1.5 on 2021-04-30 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_participants_max_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastfile',
            name='participant',
        ),
        migrations.AddField(
            model_name='participants',
            name='podcastfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.podcastfile'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='max_participant',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
