# Generated by Django 3.1.5 on 2021-04-30 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20210430_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='max_participant',
        ),
        migrations.AddField(
            model_name='podcastfile',
            name='Number_of_participant',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
