# Generated by Django 3.1.5 on 2021-04-30 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20210430_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='podcastfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.podcastfile'),
        ),
        migrations.AlterField(
            model_name='podcastfile',
            name='Number_of_participant',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
